version: '3.8'

services:
  vehicle-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=threadpilot
      - POSTGRES_PASSWORD=threadpilot
      - POSTGRES_DB=vehicledb
    ports:
      - "5433:5432"

  insurance-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=threadpilot
      - POSTGRES_PASSWORD=threadpilot
      - POSTGRES_DB=insurancedb
    ports:
      - "5434:5432"

  vehicle-service:
    build: ./threadpilot-vehicle
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vehicle-db:5432/vehicledb
      - SPRING_DATASOURCE_USERNAME=threadpilot
      - SPRING_DATASOURCE_PASSWORD=threadpilot
    depends_on:
      - vehicle-db
    volumes:
      - "${HOME}/.m2:/root/.m2"

  insurance-service:
    build: ./threadpilot-insurance
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://insurance-db:5432/insurancedb
      - SPRING_DATASOURCE_USERNAME=threadpilot
      - SPRING_DATASOURCE_PASSWORD=threadpilot
      - VEHICLE_SERVICE_BASE_URL=http://vehicle-service:8081/api/vehicles/owner/
    depends_on:
      - insurance-db
      - vehicle-service
    volumes:
      - "${HOME}/.m2:/root/.m2"




















