spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insurancedb
    driverClassName: org.postgresql.Driver
    username: threadpilot
    password: threadpilot
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml