name: Test Insurance Service
run-name: ${{ github.actor }} triggered test ${{ github.ref_name }} (${{ github.event.pull_request.base.ref }})

on:
  pull_request:
    branches:
      - staging
      - main

concurrency:
  group: ${{ github.workflow }}/${{ github.head_ref || github.ref_name || github.ref }}
  cancel-in-progress: true


jobs:
  notification-start:
    name:  Notification
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        run: echo "Notification important when pipeline is started"

  sonar-analysis:
    name: Code static analysis (Sonar or other)
    runs-on: ubuntu-latest
    steps:
      - name: perform static analysis
        run: echo "Perform static analysis"

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    needs:
      - notification-start
      - sonar-analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'corretto'
          architecture: x64
          cache: gradle

      - name: Build with Gradle
        run: cd threadpilot-insurance && ./gradlew clean build -DskipTests=true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: threadpilot-insurance/build/reports/tests/test/index.html


  notification-end:
    name: Notification
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
      - name: Notification
        run: echo "Notification important when pipeline is finished"

